# Base configs
baseurl: "https://photography.jramasani.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-218062232-1"

# UI configs
title: "Photography by Jay Reddy"
#subtitle: "See the world through my eyes!"
author: "Jay Reddy"
header:
 title: "Photo"
 subtitle: "by Jay Reddy"
footer:
 name: "Jay Reddy"
 bio: ""
 github: ""
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  #twitter: "https://www.twitter.com/jayramasani"
  instagram: "https://www.instagram.com/jramasani"
  #linkedin: "https://in.linkedin.com/in/jramasani"
  github: "https://www.github.com/jramasani"
